InnoplixTeamMgmt/InnoplixTeamMgmt/Models/Prospect.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InnoplixTeamMgmt.Models
{
    public class Prospect
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required!")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Age is required!")]
        [Range(minimum:18, maximum:99, ErrorMessage = "Age must be between 18 to 99 years only!")]
        public int? Age { get; set; }

        [Required(ErrorMessage = "Mobile Number is required!")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "City is required!")]
        public string City { get; set; }

        [Required(ErrorMessage = "Select State!")]
        [Range(1, int.MaxValue, ErrorMessage = "Select State!")]
        [Display(Name="State")]
        public int? StateId { get; set; }

        [Required(ErrorMessage = "Marital Status is required!")]
        [Range(1, int.MaxValue, ErrorMessage = "Marital Status is required!")]
        public MaritalStatus? MaritalStatus { get; set; }

        public string Ocuupation { get; set; }

        public string Income { get; set; }

        [Required(ErrorMessage = "Relation is required!")]
        public string Relation { get; set; }

        [Display(Name = "Degree Of Relation")]
        [Required(ErrorMessage = "Select Degree Of Relation!")]
        public DegreeOfRelation DegreeOfRelation { get; set; }

        [Required(ErrorMessage = "Profile is required!")]
        public Profile Profile { get; set; }

        public string Remarks { get; set; }

        [Display(Name = "Prospect Type")]
        [Required(ErrorMessage = "Select Prospect Type!")]
        public ProspectType ProspectType { get; set; }

        [ForeignKey("UserName")]
        public virtual ApplicationUser ApplicationUser { get; set; }

        public ProspectStatus ProspectStatus { get; set; }

        [ForeignKey("StateId")]
        public virtual State State { get; set; }
    }
}

InnoplixTeamMgmt/InnoplixTeamMgmt/Controllers/ProspectController.cs
using InnoplixTeamMgmt.Data;
using InnoplixTeamMgmt.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;

namespace InnoplixTeamMgmt.Controllers
{
    [Authorize]
    public class ProspectController : Controller
    {
        private readonly ILogger<ProspectController> _logger;
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProspectController(ILogger<ProspectController> logger, ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _dbContext = dbContext;
            _userManager = userManager;
        }

        public async Task<ViewResult> List()
        {
            ViewBag.Title = "Prospect List"; 
            var prospects = await _dbContext.Prospects.Include("State").ToListAsync();
            return View(prospects);
        }

        public async Task<ViewResult> Prospect(int? id = null, bool IsSuccess = false)
        {
            var stateList = await _dbContext.States.OrderBy(s => s.Name).ToListAsync();
            stateList.Insert(0, new State { Id = 0, Name = "Select State Name" });
            ViewBag.StateList = stateList;

            ViewBag.IsEdit = id.HasValue;
            ViewBag.Title = ViewBag.IsEdit ? "Edit Prospect" : "Create New Prospect";
            ViewBag.IsSuccess = IsSuccess;

            if (id.HasValue)
            {
                var prospect = await _dbContext.Prospects.FirstOrDefaultAsync(i => i.Id == id.Value);
                return View(prospect);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Prospect(Prospect model)
        {
            ApplicationUser usr = await _userManager.GetUserAsync(HttpContext.User);
            model.ApplicationUser = usr;

            var stateList = await _dbContext.States.OrderBy(s => s.Name).ToListAsync();
            stateList.Insert(0, new State { Id = 0, Name = "Select State Name" });
            ViewBag.StateList = stateList;

            ViewBag.IsEdit = model.Id != 0;
            ViewBag.Title = ViewBag.IsEdit ? "Edit Prospect" : "Create New Prospect";
            ViewBag.IsSuccess = false;

            if (ModelState.IsValid)
            {
                if (model.Id != 0)
                {
                    var prospect = await _dbContext.Prospects.FirstOrDefaultAsync(i => i.Id == model.Id);
                    prospect.Name = model.Name;
                    prospect.Age = model.Age;
                    prospect.City = model.City;
                    prospect.StateId = model.StateId;
                    prospect.Relation = model.Name;
                    prospect.DegreeOfRelation = model.DegreeOfRelation;
                    prospect.MaritalStatus = model.MaritalStatus;
                    prospect.Mobile = model.Mobile;
                    prospect.Ocuupation = model.Ocuupation;
                    prospect.Profile = model.Profile;
                    prospect.ProspectType = model.ProspectType;
                    prospect.Remarks = model.Remarks;
                    prospect.ProspectStatus = model.ProspectStatus;
                    _dbContext.SaveChanges();

                    return RedirectToAction("List");
                }
                else
                {
                    model.ProspectStatus = ProspectStatus.New;
                    _dbContext.Prospects.Add(model);
                    _dbContext.SaveChanges();

                    if(model.Id > 0)
                    {
                        return RedirectToAction(nameof(Prospect), new { IsSuccess = true });
                    }
                }
            }

            return View();
        }
    }
}

InnoplixTeamMgmt/InnoplixTeamMgmt/Views/Prospect/List.cshtml
@model IEnumerable<Prospect>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col-md-6">
                <h6 class="m-0 font-weight-bold text-primary">List of Prospects</h6>
            </div>
            <div class="col-md-6 text-right">
                <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" asp-controller="Prospect" asp-action="Prospect">New Prospect</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="bg-primary text-white">
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Mobile</th>
                        <th>Address</th>
                        <th>M/U</th>
                        <th>Relation</th>
                        <th>Occupation</th>
                        <th>Income</th>
                        <th>Profile</th>
                        <th>Edit, Details</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tfoot class="bg-gray-300">
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Mobile</th>
                        <th>Address</th>
                        <th>M/U</th>
                        <th>Relation</th>
                        <th>Occupation</th>
                        <th>Income</th>
                        <th>Profile</th>
                        <th>Edit, Details</th>
                        <th>Status</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var pros in Model)
                    {
                        <tr>
                            <td>@pros.Name</td>
                            <td>@pros.Age</td>
                            <td>@pros.Mobile</td>
                            <td>@pros.City, @pros.State.Code</td>
                            <td>@pros.MaritalStatus</td>
                            <td>@pros.Relation (@pros.DegreeOfRelation)</td>
                            <td>@pros.Ocuupation</td>
                            <td>@pros.Income</td>
                            <td>@pros.Profile</td>
                            <td>
                                <a asp-controller="Prospect" asp-action="Prospect" asp-route-id="@pros.Id" title="Edit"><i class="fas fa-pen-square" aria-hidden="true"></i></a>&nbsp;&nbsp;
                                <a href="#" title="Details"><i class="fas fa-desktop" aria-hidden="true"></i></a>
                            </td>
                            <td><a href="#">@pros.ProspectStatus</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Style
{
    <!-- Custom styles for this page -->
    <link href="~/theme/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <style type="text/css">
        .table td, .table th {
            padding: .30rem;
        }

        .table.table-bordered.dataTable thead th,
        .table.table-bordered.dataTable tfoot th,
        .table.table-bordered.dataTable tbody td {
            font-size:smaller;
        }

    </style>
}

@section Scripts
{
    <!-- Page level plugins -->
    <script src="~/theme/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/theme/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/theme/js/demo/datatables-demo.js"></script>
}

InnoplixTeamMgmt/InnoplixTeamMgmt/Views/Prospect/Prospect.cshtml
@model InnoplixTeamMgmt.Models.Prospect

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col-md-6">
                <h6 class="m-0 font-weight-bold text-primary">@(ViewBag.IsEdit ? "Edit Prospect" : "Create New Prospect")</h6>
            </div>
            <div class="col-md-6 text-right">
                <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" asp-controller="Prospect" asp-action="List">Back to List</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        @if (ViewBag.IsSuccess)
        {
            <div class="card bg-success text-white shadow">
                <div class="card-body">
                    Congratulations! You have added new prospect in your list successfully.
                </div>
            </div>
        }
        <form asp-action="Prospect">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @if (ViewBag.IsEdit)
                {
                    <input type="hidden" asp-for="Id" />
                }
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" maxlength="2" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label"></label>
                    <input asp-for="Mobile" class="form-control" />
                    <span asp-validation-for="Mobile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StateId" class="control-label"></label>
                    <select asp-for="StateId" class="form-control" asp-items="@(new SelectList(ViewBag.StateList,"Id","Name"))"></select>
                    <span asp-validation-for="StateId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MaritalStatus" class="control-label"></label>
                    <select asp-for="MaritalStatus" class="form-control" asp-items="Html.GetEnumSelectList<MaritalStatus>()">
                        <option>Please select marital status</option>
                    </select>
                    <span asp-validation-for="MaritalStatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ocuupation" class="control-label"></label>
                    <input asp-for="Ocuupation" class="form-control" />
                    <span asp-validation-for="Ocuupation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Income" class="control-label"></label>
                    <input asp-for="Income" class="form-control" />
                    <span asp-validation-for="Income" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Relation" class="control-label"></label>
                    <input asp-for="Relation" class="form-control" />
                    <span asp-validation-for="Relation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DegreeOfRelation" class="control-label"></label>
                    <select asp-for="DegreeOfRelation" class="form-control" asp-items="Html.GetEnumSelectList<DegreeOfRelation>()">
                        <option>Please select degree of relation</option>
                    </select>
                    <span asp-validation-for="DegreeOfRelation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Profile" class="control-label"></label>
                    <select asp-for="Profile" class="form-control" asp-items="Html.GetEnumSelectList<Profile>()">
                        <option>Please select profile</option>
                    </select>
                    <span asp-validation-for="Profile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProspectType" class="control-label"></label>
                    <select asp-for="ProspectType" class="form-control" asp-items="Html.GetEnumSelectList<ProspectType>()">
                        <option>Please select prospect type</option>
                    </select>
                    <span asp-validation-for="ProspectType" class="text-danger"></span>
                </div>
                @if (ViewBag.IsEdit)
                {
                    <div class="form-group">
                        <label asp-for="ProspectStatus" class="control-label"></label>
                        <select asp-for="ProspectStatus" class="form-control" asp-items="Html.GetEnumSelectList<ProspectStatus>()">
                            <option>Please select prospect status</option>
                        </select>
                        <span asp-validation-for="ProspectStatus" class="text-danger"></span>
                    </div>
                }
                <div class="form-group">
                    <label asp-for="Remarks" class="control-label"></label>
                    <input asp-for="Remarks" class="form-control" multiple />
                    <span asp-validation-for="Remarks" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>                
        </form>
    </div>
</div>